apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: counter-backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: counter-backend
  minReplicas: 2
  maxReplicas: 2
  targetCPUUtilizationPercentage: 50
