apiVersion: v1
kind: Secret
metadata:
  name: counter-database
  labels:
    app: counter-app
type: Opaque
data:
  #database-host: Y291bnRlci1kYXRhYmFzZQo=
  database-name: ZGF0YWJhc2UK
  database-user: dXNlcgo=
  database-password: cGFzc3dvcmQK
