apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: counter-app
  template:
    metadata:
      labels:
        app: counter-app
    spec:
      containers:
      - name: counter-database
        image: registry.redhat.io/rhel8/postgresql-15:latest
        ports:
          - containerPort: 5432
        volumeMounts:
          - name: counter-database-data
            mountPath: /var/lib/pgsql/data
        env:
          - name: POSTGRESQL_USER
            valueFrom:
              secretKeyRef:
                name: counter-database
                key: database-user
          - name: POSTGRESQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: counter-database
                key: database-password
          - name: POSTGRESQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: counter-database
                key: database-name
      volumes:
        - name: counter-database-data
          persistentVolumeClaim:
            claimName: counter-database-data
