apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: counter-database-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: rbd-storagepool-cluster
  volumeMode: Filesystem
