apiVersion: v1
kind: Service
metadata:
  name: counter-database
  labels:
    app: counter-app
spec:
  selector:
    app: counter-app
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
